import type { Metadata } from 'next'
import { Red_Hat_Display } from 'next/font/google'

import './globals.css'
import { Header } from '../components/Header'
import { Footer } from '@/components/Footer'

const mainFontFamily = Red_Hat_Display({
  weight: ['400', '700', '800'],
  subsets: ['latin'],
  variable: '--font-family-main',
})

export const metadata: Metadata = {
  title: 'Varos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className={mainFontFamily.variable}>
      <body>
        <div className="min-h-screen bg-varosPrincipalDark">
          <Header />

          <main>{children}</main>

          <Footer />
        </div>
      </body>
    </html>
  )
}
